---
title: "Migration towards Pdgfb Plate 1"
author: "Jordi Camps"
date: "23 December 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load packages
```{r message=FALSE}
library(readxl)
library(tidyr)
library(dplyr)
library(ggplot2)
library(ggpubr)
```

## Load data
```{r}
df <- read_excel("data/fig5-6_migration/Transwell_migration_pdgf_Plate_1.xlsx", col_names = TRUE)
head(df)
```

## Create factors
compound
```{r}
df$compound <- plyr::revalue(df$compound, c(`Assay buffer` = "Negative_control", `PDGF-BB 25ng` = "Pdgfb", `30% FBS` = "Positive_control"))
df$compound <- factor(df$compound, levels = c("Negative_control", "Pdgfb", "Positive_control"))
```

genotype
```{r}
df$genotype <- plyr::revalue(df$genotype, c(SGCB2 = "Dystrophic", WT = "Healthy"))
df$genotype <- factor(df$genotype, levels = c("Healthy", "Dystrophic"))
```

Celltype
```{r}
df$celltype <- factor(df$celltype, levels = c("MAB", "FAP"))
```

## Statistics
```{r}
compare_means(percentage ~ genotype, data = df, group.by = c("celltype", "compound"))
```


## Plot
```{r fig.height=2.5, fig.width=6}
compound_titles <- c(Negative_control = "Negative\ncontrol", Pdgfb = "PDGF-BB", Positive_control = "Positive\ncontrol")
df %>%
  ggplot(aes(x = celltype, y = percentage, fill = genotype)) +
  geom_boxplot() +
  facet_wrap(~compound, scales = "free_y", labeller = labeller(compound = compound_titles)) +
  scale_y_continuous("Percentage", expand = c(0, 1), limits = c(0, 30)) +
  stat_compare_means(label = "p.signif", label.x = 1) +
  ggthemes::scale_fill_tableau() +
  theme_bw(base_size = 14) +
  theme(panel.border = element_blank(), 
        panel.grid = element_blank(), 
        axis.line = element_line(colour = "black"),
        axis.ticks.y = element_line(colour = "black"), 
        axis.text = element_text(colour = "black"), 
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        legend.title = element_blank(),
        strip.background = element_blank(),
        strip.text = element_text(face = "italic")
        )
ggsave("plots/migration/percentage_migration_plate_1.pdf", dpi = 600)
ggsave("plots/migration/percentage_migration_plate_1.png", dpi = 600)
```

Plot filtered plots
```{r fig.height=2, fig.width=5}
compound_titles <- c(Negative_control = "Negative\ncontrol", Pdgfb = "PDGF-BB", Positive_control = "Positive\ncontrol")
df$compound <- plyr::revalue(df$compound, compound_titles)
```

```{r fig.height=3.5, fig.width=7}
my_comparisons = list(c("Negative\ncontrol", "PDGF-BB"), c("Negative\ncontrol", "Positive\ncontrol"), c("PDGF-BB", "Positive\ncontrol"))
df %>%
  filter(genotype == "Healthy" & celltype == "FAP" | genotype == "Dystrophic" & celltype == "MAB") %>%
  ggplot(aes(x = compound, y = percentage, col = compound)) +
  geom_boxplot(size = 1.2, outlier.shape = NA) +
  geom_jitter(width = 0.3, size = 2) +
  facet_wrap(~celltype, strip.position = "bottom") +
  scale_y_continuous("Percentage") +
  stat_compare_means(label = "p.signif", label.x = 1, method = "t.test", comparisons = my_comparisons) +
  #stat_compare_means(label.y = 50) +
  #ggthemes::scale_fill_tableau() +
  scale_color_brewer(type = "qual", palette = "Accent") +
  theme_bw(base_size = 16) +
  theme(panel.border = element_blank(), 
        panel.grid = element_blank(), 
        axis.line = element_line(colour = "black"),
        axis.ticks.y = element_line(colour = "black"), 
        axis.text = element_text(colour = "black"), 
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        legend.title = element_blank(),
        strip.background = element_blank(),
        strip.text = element_text(face = "italic"),
        axis.text.x = element_blank(),
        strip.placement = "outside",
        legend.key.height = unit(0, "cm"),
        plot.margin = unit(c(0.5, 0, 0, 0.5), "lines")
        )
ggsave("plots/migration/percentage_migration_plate_1_filtered.pdf", dpi = 600)
ggsave("plots/migration/percentage_migration_plate_1_filtered.png", dpi = 600)
```


## Chemotactic index
```{r}
ci <- df %>%
  select(compound, genotype, celltype, percentage) %>%
  group_by(celltype, genotype, compound) %>%
  summarise(replicates = n(),
            perc_avg = mean(percentage, na.rm = TRUE),
            perc_sem = sd(percentage, na.rm = TRUE) / sqrt(replicates) / perc_avg * 100) %>%
  gather(key, value, -(celltype:replicates)) %>%
  unite(col = key, compound, key) %>%
  spread(key, value) %>%
  mutate(CI_pdgfb = Pdgfb_perc_avg / Negative_control_perc_avg,
         SEM_pdgfb = sqrt((Pdgfb_perc_sem)^2 + (Negative_control_perc_sem)^2) * CI_pdgfb / 100,
         CI_posctrl = Positive_control_perc_avg / Negative_control_perc_avg,
         SEM_posctrl = sqrt((Positive_control_perc_sem)^2 + (Negative_control_perc_sem)^2) * CI_posctrl / 100) %>%
  select(celltype, genotype, CI_pdgfb, SEM_pdgfb, CI_posctrl, SEM_posctrl) %>%
  gather(key, value, (CI_pdgfb:SEM_posctrl)) %>%
  separate(key, c("variable", "compound"), sep = "_") %>%
  spread(variable, value) %>%
  mutate(ylower = CI - SEM,
         yupper = CI + SEM)
```

## Plot
```{r fig.height=3, fig.width=6}
compound_titles <- c(pdgfb = "Pdgfb", posctrl = "Positive control")
ci %>%
  ggplot(aes(x = celltype, y = CI, fill = genotype)) +
  geom_col(position = position_dodge(), width = 0.8) +
  geom_errorbar(aes(ymin = ylower, ymax = yupper), position = position_dodge(0.8), width = 0.2) +
  #geom_pointrange(aes(ymin = ylower, ymax = yupper), position = position_dodge(0.8)) +
  facet_wrap(~compound, scales = "free_y", labeller = labeller(compound = compound_titles)) +
  scale_y_continuous("Chemotactic index", expand = c(0, 0)) +
  ggthemes::scale_fill_tableau() +
  theme_bw(base_size = 16) +
  theme(panel.border = element_blank(), panel.grid = element_blank(), strip.background = element_blank(), axis.line = element_line(colour = "black"),
        axis.ticks.y = element_line(colour = "black"), axis.text = element_text(colour = "black"), axis.title.x = element_blank(),
        legend.title = element_blank(), strip.text = element_text(face = "italic"), axis.ticks.x = element_blank())
ggsave("plots/migration/chemotactic_index_plate_1.pdf", dpi = 600)
ggsave("plots/migration/chemotactic_index_plate_1.png", dpi = 600)
```

## Statistics
```{r}
t_data <- list()
for (i in 1:2) {
  for (j in 1:3) {
    temp <- df %>%
      filter(celltype == as.character(unique(df$celltype))[i] & compound == as.character(unique(df$compound))[j])
    t <- t.test(percentage~genotype, data = temp)
    t_data[[3*(i-1)+j]] <- c(p_value = t$p.value, celltype = as.character(unique(df$celltype))[i], compound = as.character(unique(df$compound))[j])
  }
} 
```

```{r}
head(t_data)
```

Create df from statistical list
```{r}
stat <- as.data.frame(t(as.data.frame(t_data, stringsAsFactors = FALSE)), stringsAsFactors = FALSE)
stat$p_value <- as.numeric(stat$p_value)
rownames(stat) <- NULL
head(stat)
```

Merge with ci
```{r}
stat$compound <- plyr::revalue(stat$compound, c(Negative_control = "negctrl", Pdgfb = "pdgfb", Positive_control = "posctrl"))
ci %>%
  inner_join(stat, by = c("celltype", "compound"))
```

